---
- hosts: 
  tasks:
    - name: adding docker repo
      get_url: 
         url: https://download.docker.com/linux/centos/docker-ce.repo
         dest: /etc/yum.repos.d/
    - name: remove the bug
      replace:
         path: /etc/yum.repos.d/docker-ce.repo
         regexp: rhel
         replace: centos
    - name: installing the docker software
      package:
        name: docker
        state: present
    - name: starting the service of docker
      service:
        name: docker
        state: started
        enabled: yes
    - name: installing the docker sdk-python
      pip:
        name: docker-py
    - name:  Downloading the image
      docker_image:
        name: "ununtu"
        tag: "14.04"
    - name: Launching the container
      docker_container: 
        name: infinity
        state: started
        image: ubuntu:14.04
        command: sleep infinity
        
          
        
